instances_username: ''
private_key_file_path: ''
manager:
  external_certificates: {external_cert_path: '', external_key_path: '', external_new_ca_cert_path: ''}
  new_ca_cert_path: ''
  new_ca_key_path: ''
  nodes:
  - {host_ip: 172.12.0.71, new_cert_path: '', new_key_path: ''}
  - {host_ip: 172.12.0.72, new_cert_path: '', new_key_path: ''}
  - {host_ip: 172.12.0.73, new_cert_path: '', new_key_path: ''}
db:
  new_ca_cert_path: ''
  nodes:
  - {host_ip: 172.12.0.74, new_cert_path: '', new_key_path: ''}
  - {host_ip: 172.12.0.90, new_cert_path: '', new_key_path: ''}
  - {host_ip: 172.12.0.92, new_cert_path: '', new_key_path: ''}
broker:
  new_ca_cert_path: ''
  nodes:
  - {host_ip: 172.12.0.93, new_cert_path: '', new_key_path: ''}
  - {host_ip: 172.12.0.94, new_cert_path: '', new_key_path: ''}
  - {host_ip: 172.12.0.95, new_cert_path: '', new_key_path: ''}
