#!/bin/bash
#
# Perform necessary cloudify setup steps
# after package is installed.
#

PROGNAME=$(basename $0)

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

if [[ "$OSTYPE" == "darwin"* ]]; then
    INSTALLER_DIR="/usr/local/opt/cfy"
    PREFIX="/usr/local"
    mkdir -p "$PREFIX/bin"
else
    INSTALLER_DIR="/opt/cfy"
    PREFIX="/usr"
fi

ln -sf $INSTALLER_DIR/embedded/bin/cfy $PREFIX/bin || error_exit "Cannot link cfy to $PREFIX/bin"

echo "Thank you for installing Cloudify!"

exit 0
