#!/bin/bash
#
# Perform necessary cloudify setup steps
# after package is installed.
#

PROGNAME=$(basename $0)
INSTALLER_DIR="/opt/cfy"
PREFIX="/usr"

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

is_darwin()
{
  uname -v | grep "^Darwin" 2>&1 >/dev/null
}

if is_darwin; then
    PREFIX="/usr/local"
    mkdir -p "$PREFIX/bin"
else
    PREFIX="/usr"
fi

ln -sf $INSTALLER_DIR/bin/cfy $PREFIX/bin || error_exit "Cannot link cfy to $PREFIX/bin"

echo "Thank you for installing Cloudify!"

exit 0
