apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: jenkins/inbound-agent
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  - name: py36
    image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-python3.6
    resources:
      requests:
        cpu: 0.6
        memory: 1Gi
      limits:
        cpu: 0.6
        memory: 1Gi
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: rpmbuild
    image: 263721492972.dkr.ecr.eu-west-1.amazonaws.com/cloudify-rpmbuild
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      requests: 
        cpu: 1.4
        memory: 2Gi
      limits:
        cpu: 2
        memory: 4Gi
  - name: py27
    image: circleci/python:2.7
    resources:
      requests:
        cpu: 0.6
        memory: 1Gi
      limits:
        cpu: 0.6
        memory: 1Gi
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: debbuild
    image: ubuntu:18.04
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      limits:
        cpu: 0.5
        memory: 1Gi
  - name: awscli
    image: amazon/aws-cli
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot-xlarge
