apiVersion: v1
kind: Pod
spec:
  containers:
  - name: py36
    image: circleci/python:3.6
    resources:
      requests:
        cpu: 1
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: py37
    image: circleci/python:3.7
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: py38
    image: circleci/python:3.8
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: py39
    image: circleci/python:3.9
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: rpmbuild
    image: rpmbuild/centos7
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: py27
    image: circleci/python:2.7
    resources:
      requests:
        cpu: 0.6
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: debbuild
    image: ubuntu:18.04
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  nodeSelector:
    instance-type: spot