apiVersion: v1
kind: Pod
spec:
  containers:
  - name: py36
    image: circleci/python:3.6
    resources:
      requests:
        cpu: 1
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: rpmbuild
    image: rpmbuild/centos7
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 1
    securityContext:
      runAsUser: 0
      privileged: true
  - name: py27
    image: circleci/python:2.7
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true