apiVersion: v1
kind: Pod
spec:
  containers:
  - name: py36
    image: circleci/python:3.6
    resources:
      requests:
        cpu: 0.3
        memory: 512Mi
      limits:
        cpu: 1.5
        memory: 512Mi
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
  - name: rpmbuild
    image: rpmbuild/centos7
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      requests:
        cpu: 0.4
        memory: 512Mi
      limits:
        cpu: 1.5
        memory: 512Mi
  - name: py27
    image: circleci/python:2.7
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      requests:
        cpu: 0.3
        memory: 512Mi
      limits:
        cpu: 1.5
        memory: 512Mi
  - name: debbuild
    image: ubuntu:18.04
    command:
    - cat
    tty: true
    securityContext:
      runAsUser: 0
      privileged: true
    resources:
      requests:
        cpu: 0.4
        memory: 512Mi
      limits:
        cpu: 1.5
        memory: 512Mi
  - name: awscli
    image: amazon/aws-cli
    command:
    - cat
    tty: true
    resources:
      limits:
        cpu: 0.2
        memory: 256Mi
  imagePullSecrets:
    - name: dockerhub
  nodeSelector:
    instance-type: spot
